#!/usr/bin/env sh

DESC="kicker slack app"
NAME=kicker
PIDFILE=/var/run/$NAME.pid
RUN_AS=kicker
WORK_DIR=/opt/kicker
DAEMON=/usr/bin/java
OPTS="-jar -Dlog4j.configurationFile=/opt/kicker/conf/log4j2.xml /opt/kicker/lib/kicker-all.jar"

do_start() {
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
        --background --chdir $WORK_DIR \
        --user $RUN_AS \
        --exec $DAEMON -- $OPTS
}

do_stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    if [ -e $PIDFILE ]
        then rm $PIDFILE
    fi
}

case "$1" in
    start)
    echo -n "Starting $DESC: $NAME"
    do_start
    echo "."
    ;;
    stop)
    echo -n "Stopping $DESC: $NAME"
    do_stop
    echo "."
    ;;
    restart)
    echo -n "Restarting $DESC: $NAME"
    do_stop
    sleep 1
    do_start
    echo "."
    ;;
    status)
    . /lib/lsb/init-functions
    status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
    *)
    echo "usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac
